### ISSUE TITLE
Example fails to build with up-to-date opam-repository

### ISSUE THREAD

**Issue by LogicalOverflow** [RyanGibb/hillingar#11]
Updating the flake inputs of the [example repo](https://github.com/RyanGibb/mirage-hello-hillingar) causes it to fail to build
since the release of `ptime.1.1.0`, even when ensuring ocaml 4 is used.

This invocation fails to build (my fork just updates the `flake.lock` and adds `package "ocaml" ~max:"5.0.0"` to the `packages` in the `config.ml`):
```bash
nix build "github:LogicalOverflow/mirage-hello-hillingar" --override-input opam-repository \
    "github:ocaml/opam-repository?rev=49c3ad31df3f2f60c2006211900b6553c097277c"
```
With the following error:
```
File "duniverse/mirage-logs/src/dune", line 4, characters 50-55:
4 |   (libraries logs mirage-clock lwt mirage-profile ptime))
                                                      ^^^^^
Error: Library "ptime" not found.
-> required by library "mirage-logs" in
   _build/default/duniverse/mirage-logs/src
-> required by executable main in dune.build:12
-> required by _build/default/main.exe
-> required by _build/default/hello
-> required by _build/default/dist/hello
-> required by alias dist/all
-> required by alias dist/default
```
The previous commit of `opam-repository` still works:
```bash
nix build "github:LogicalOverflow/mirage-hello-hillingar" --override-input opam-repository \
    "github:ocaml/opam-repository?rev=29869b0a1ad4fb7fc4a08d8a888a7abb6d0fa5cc"
```
The first bad commit is https://github.com/ocaml/opam-repository/commit/49c3ad31df3f2f60c2006211900b6553c097277c, which adds `ptime.1.1.0`

I am not sure yet, where the issue lies (here, with opam-nix or somewhere else), but I am still able to build the example unikernel without nix. (`mirage configure -t unix` followed by `make`) 

As a work-around, adding `package "ptime" ~max:"1.1.0"` to the `packages` in the `config.ml` allows the build with nix to work again.

**Comment by RyanGibb** [comment]
The reason dune isn't picking up `ptime.1.1.0` from the monorepo is because it isn't built with dune. We use the overlay for v1.0.0 here: https://github.com/dune-universe/opam-overlays/blob/master/packages/ptime/ptime.1.0.0%2Bdune/opam, but no such overlay has been created for v1.1.0 (yet). (More info on these overlays here: https://github.com/dune-universe/opam-overlays.)

Building outside the nix derivation with `make` uses the [`opam monorepo`](https://github.com/tarides/opam-monorepo) solver which filters out non-dune dependent packages so that only those with overlays are returned. We're using `opam`'s default solver which *doesn't* filter out non-dune dependent packages, hence this problem. This issue is tracked here: https://github.com/RyanGibb/hillingar/issues/3

I also tried to build a repository for using the solver on that had the non-dune dependent packages filtered out, but that was ridiculously slow: https://github.com/tweag/opam-nix/pull/18#discussion_r968562048.

Until #3 is resolved, manually specifying the dependency version seems like a reasonable workaround.

**Comment by LogicalOverflow** [comment]
Thanks for the insight. I'll close this issue then, as it's a duplicate of https://github.com/RyanGibb/hillingar/issues/3.
